server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    error_page 404 /index.html;

    location / {
        return 404;
    }

    location = /index.html {
        internal;
    }

    location = /404-background.png {
        try_files /404-background.png =404;
    }
}
